In [2]:
import torch
import tqdm

In [26]:
head_index, tail_index = torch.tensor([0, 1, 1, 2]), torch.tensor([3, 4, 5, 6])
rel_type = 1 # only one relation type to test- user item
num_test_users = max(head_index) + 1
train_edge_label_index = torch.tensor([[0, 1], [4, 6]])
num_users = 3
num_items = 4
arange = range(num_test_users)
k = 2
# arange = tqdm(arange)

precision = recall = total_hit = 0
for h in arange:
    scores = []
    tail_indices = torch.arange(num_users, num_users + num_items)
    for ts in tail_indices.split(2):
        scores.append(ts/10)
    scores = torch.cat(scores)
    label_index = tail_index[head_index == h] - num_users
    train_label_index = train_edge_label_index[1][train_edge_label_index[0] == h] - num_users
    print("train", train_label_index)
    print(scores)
    scores[train_label_index] = float('-inf')
    print(scores)
    topk_index = scores.topk(k, dim=-1).indices
    print(topk_index)
    print(label_index)
    num_hits = torch.isin(label_index, topk_index).sum().item()
    print("num hits", num_hits)
    total_hit += num_hits > 0
    precision += num_hits / k
    recall += num_hits / len(label_index)
    print("hit", num_hits > 0, "precision", num_hits / k, "recall", num_hits / len(label_index))

precision /= num_test_users
recall /= num_test_users

precision / num_test_users, recall / num_test_users, total_hit / num_test_users

train tensor([1])
tensor([0.3000, 0.4000, 0.5000, 0.6000])
tensor([0.3000,   -inf, 0.5000, 0.6000])
tensor([3, 2])
tensor([0])
num hits 0
hit False precision 0.0 recall 0.0
train tensor([3])
tensor([0.3000, 0.4000, 0.5000, 0.6000])
tensor([0.3000, 0.4000, 0.5000,   -inf])
tensor([2, 1])
tensor([1, 2])
num hits 2
hit True precision 1.0 recall 1.0
train tensor([], dtype=torch.int64)
tensor([0.3000, 0.4000, 0.5000, 0.6000])
tensor([0.3000, 0.4000, 0.5000, 0.6000])
tensor([3, 2])
tensor([3])
num hits 1
hit True precision 0.5 recall 1.0


(tensor(0.1667), tensor(0.2222), tensor(0.6667))

In [4]:
torch.arange(num_test_users)

tensor([0, 1, 2])